### ISSUE TITLE
SerializedName ignored when using IdenticalPropertyNamingStrategy

### ISSUE THREAD

**Issue by eschwartz** [schmittjoh/serializer#334] opened 2014-09-10 17:45 UTC
It appears as though the `@SerializedName` annotation is being ignored, when used with the `IdenticalPropertyNamingStrategy`.

My user class

``` php
// MyApp\Model\User

namespace MyApp\Model;

use JMS\Serializer\Annotation as JMS;

/**
 * User
 */
class User {
  /**
   * @var integer
   *
   * @JMS\SerializedName("foo")
   */
  private $someProp;

  // ...
}
```

Instantiating the serializer (I'm using ZF2, so this is a service factory)

``` php
return array(
  // ...
  'service_manager' => array(
    'factories' => array(
      'jms_serializer' => function() {
        \Doctrine\Common\Annotations\AnnotationRegistry::registerAutoloadNamespace(
          'JMS\Serializer\Annotation',
          __DIR__ . '/../../../vendor/jms/serializer/src'
        );

        $namingStrategy = new \JMS\Serializer\Naming\IdenticalPropertyNamingStrategy();
        return \JMS\Serializer\SerializerBuilder::create()
          ->setCacheDir(__DIR__ . '/../../../data/cache')
          ->setPropertyNamingStrategy($namingStrategy)
          ->build();
      }
    )
  )
);
```

With this setup, the `User` object is being serialized a `{ "someProp": "someValue" }`. I would expect it to be serialized as `{  "foo": "someValue" }`

I believe the issue is within the `JMS\Serializer\Naming\IdenticalPropertyNamingStrategy`:

``` php
class IdenticalPropertyNamingStrategy implements PropertyNamingStrategyInterface
{
    public function translateName(PropertyMetadata $property)
    {
        return $property->name;
    }
}
```

If I override the `translateName` method to check for a `serializedName` property, my issue is fixed.

``` php
       public function translateName(PropertyMetadata $property) {
        if ($property->serializedName) {
            return $property->serializedName;
        }
        return $property->name;
    }
```

I can submit a pull request to fix this -- I just want to check that I'm going about this the right way, first.

**Comment by SchizoDuckie** [comment] 2015-02-03 12:19
This should be fixed indeed. It's a nasty one to stumble upon and figure out.

Steps to fix for those coming after me:

- added @m14t's IdenticalUnlessSpecified strategy to my project
- change config.yml parameters: 
``jms_serializer.serialized_name_annotation_strategy.class: My\Name\Space\Serializer\IdenticalUnlessSpecifiedPropertyNamingStrategy``

**Comment by jlekowski** [comment] 2015-09-22 12:48
My solutions is:
```yml
services:
    jms_serializer.camel_case_naming_strategy:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'
```
as SerializedNameAnnotationStrategy is used by default, but a fallback it has is CamelCaseNamingStrategy which for some reason does not camel case column names. Now IdenticalPropertyNamingStrategy becomes the fallback and it works is SerializedName annotation is not present.

**Comment by renatomefidf** [comment] 2016-03-01 10:22
I found the same issue!

My solution was to replace the name strategy with a compiler pass to my own strategy which is:
```
class IdenticalPropertyNamingStrategy implements PropertyNamingStrategyInterface
{
    public function translateName(PropertyMetadata $property)
    {
        return $property->serializedName ?: $property->name;
    }
}
```

**Comment by jhuiting** [comment] 2016-04-19 08:56
Also ran into this issue of ignore the serializedName, fixed it by implementing a custom as well. @schmittjoh is this expected behaviour or should it be fixed?

**Comment by Sgoettschkes** [comment] 2016-10-22 12:09
Came across this today as well. One solution (for me) would be to add an additional strategy to the serializer which does this and not change the original one (not breaking old code that way).

**Comment by alexbusu** [comment] 2017-01-19 17:26
Try this:
```php
$serializer = \JMS\Serializer\SerializerBuilder::create()
    ->setPropertyNamingStrategy(
        new SerializedNameAnnotationStrategy(
            new IdenticalPropertyNamingStrategy()
        )
    )
    ->build();
```
So I'm setting the property naming strategy to `SerializedNameAnnotationStrategy()` with `IdenticalPropertyNamingStrategy()` as a property naming strategy delegate for properties without the `@SerializedName` annotation.

**Comment by bobvandevijver** [comment] 2018-02-13 19:38
So, this issue is nearly 3.5 years old, and it still isn't fixed. 

According to the [docs](https://jmsyst.com/libs/serializer/master/reference/annotations#serializedname), you can define a name, otherwise it will take the strategy name. This isn't the case at this moment.

For now, I will overwrite the strategy myself.

**Comment by goetas** [comment] 2018-02-15 12:00
@bobvandevijver the solution by @alexbusu is how it should be done it you are using the standalone serializer

**Comment by goetas** [comment] 2018-02-15 12:04
Closing as it is not a bug. If you are using a the library (without the symfony bundle), the approach used by @alexbusu is the right way to register a new naming strategy.


```php
$serializer = \JMS\Serializer\SerializerBuilder::create()
    ->setPropertyNamingStrategy(
        new SerializedNameAnnotationStrategy(
            new IdenticalPropertyNamingStrategy()
        )
    )
    ->build();
```

For who is using the bundle, please open an issue on https://github.com/schmittjoh/JMSSerializerBundle

**Closed by goetas** 2018-02-15 12:04 UTC
Labels: question

**Comment by bobvandevijver** [comment] 2018-02-15 17:33
The documentation should at least mention that the SerializedName annotation breaks at the moment you use a anything else than the default configuration.

**Comment by goetas** [comment] 2018-02-15 17:38
That is true, PW are welcome. Maybe the example from @alexbusu is already ok

Doc are here https://github.com/schmittjoh/serializer/tree/master/doc
