### ISSUE TITLE
Object to array normalization

### ISSUE THREAD

**Issue by alsma** [schmittjoh/serializer#354] opened 2014-10-16 14:03 UTC
Hello! 

Currently I'm working on unified API implementation for our project, and I'd like to use serializer for REST api serialization/deserialization.
But also we are looking to reuse metadata that required for JMSSerializer in our SOAP api implementation. I see that normalization/denormalization logic  are coupled together in visitors. Could you please assist how we can use serializer in order to do `array -> object` denormalization and vise versa ?

**Comment by davidwindell** [comment] 2015-02-22 00:54
Duplicate of #20

**Closed** 2017-03-21 11:52 UTC
