### ISSUE TITLE
Integer serialized as String using VirtualProperty

### ISSUE THREAD

**Issue by ClementGautier** [schmittjoh/serializer#289] opened 2014-06-30 09:52 UTC
Hi,

``` php
    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("mood")
     *
     * @return string
     */
    public function getSomeMethod()
    {
        return 42;
    }
```

is serialized as a string in my json output.

**Comment by bkosborne** [comment] 2015-07-07 15:22
I have the same issue, trying to find a solution.

**Comment by goetas** [comment] 2017-04-24 15:12
Closing, Sorry for the long feedback loop. This issue has been probably already solved, if the problem is still here, feel free to comment it and I will re-open the issue

**Closed by goetas** 2017-04-24 15:12 UTC
