### ISSUE TITLE
Max Depth possible issue

### ISSUE THREAD

**Issue by mamartins** [schmittjoh/serializer#272] opened 2014-05-12 15:14 UTC
Hello,

I'm using this bundle in conjunction with FOS rest bundle to create an API. I fell the need of using the max Depth parameter and I think that it is not working as supposed.

Let me explain my use case.

I have 2 entities:
- State
- StateWorkflow

State fields:
- id
- name
- initial (boolean)
  and a oneToMany relation with stateWorkflow:
- stateWorkflow [mappedBy: initialState]

StateWorkflow fields:
- id
- action
  and 2 manyToOne relations with State
- initialState
- finalState

So, there is only one bi-directional relation that is between stateWorkflow and initial State. The goal here is be able to know the available states that a State, if it is an initialState, can go to, that are the final states.

Since the serialization of the State without max_depth property can produce a lot of nesting on the stateWorkflow and I only need to have the first level which not have the StateWorkflow from initialState and finalState I used the max_depth option.
eg of the wanted json result:

``` json
[
  {
    "id": 1,
    "name": "onHold",
    "initial": true,
    "state_workflow": [
      {
        "id": 1,
        "final_state": {
          "id": 2,
          "name": "sellable",
          "initial": false,
          "state_workflow": []
        },
        "action": "doom"
      }
    ]
  },
  {
    "id": 2,
    "name": "sellable",
    "initial": false,
    "state_workflow": [
      {
        "id": 4,
        "final_state": {
          "id": 1,
          "name": "onHold",
          "initial": true,
          "state_workflow": []
        },
        "action": "un-doom"
      },
      {
        "id": 5,
        "final_state": {
          "id": 3,
          "name": "sold",
          "initial": false,
          "state_workflow": []
        },
        "action": "sell"
      }
    ]
  }
]
```

with this I can tell that for eg the state onHold can go to the sellable through the action doom.

Since this is the first level of depth in stateWorkflow field of the State entity and because I also want the nested State on it, I thought that I needed to set `max_depth: 2`, but I can only achieve the desired result by setting  `max_depth: 3`
If I set it to 1 I got:

``` json
{
  "0": {
    "id": 1,
    "name": "onHold",
    "initial": true,
    "state_workflow": [
      {}
    ]
  },
  "1": {
    "id": 2,
    "name": "sellable",
    "initial": false,
    "state_workflow": [
      {},
      {}
    ]
  },
  "2": {
    "id": 3,
    "name": "sold",
    "initial": false,
    "state_workflow": []
  }
}
```

and with `max_depth: 2`:

``` json
[
  {
    "id": 1,
    "name": "onHold",
    "initial": true,
    "state_workflow": [
      {
        "id": 1,
        "action": "doom"
      }
    ]
  },
  {
    "id": 2,
    "name": "sellable",
    "initial": false,
    "state_workflow": [
      {
        "id": 4,
        "action": "un-doom"
      },
      {
        "id": 5,
        "action": "sell"
      }
    ]
  },
  {
    "id": 3,
    "name": "sold",
    "initial": false,
    "state_workflow": []
  }
]
```

Is this the expected behaviour? I can understand why I should set the max_depth to 2 to get what I expected, but not 3. 

In my opinion, and what looks more clear is that Max_depth 1 should at least show the stateWorkflow fields that don't are relations, which is what I get when I set it to 2.

According to the documentation about this feature what I interpreted is that I needed to set it to 2:

```

In this example, serializing a user, because the max depth of the $friends property is 1, the user friends would be serialized, but not their friends; and because the the max depth of the $posts property is 2, the posts would be serialized, and their author would also be serialized.
```

**Comment by alexandrubau** [comment] 2017-06-28 08:46
I recently stumbled upon this issue too.
When serializing a Collection (Doctrine\Common\Collections\Collection) max_depth doesn't work as intended. The workaround I found is to call `$collection->toArray()` before serializing it.

**Comment by goetas** [comment] 2018-04-15 09:30
fixed in https://github.com/schmittjoh/serializer/pull/743/commits/94c319db88883757a14ac267115272be030aef28

**Closed by goetas** 2018-04-15 09:30 UTC
Labels: bug
