### ISSUE TITLE
Where in the JMS code does the navigator call VisitProperty method for visitor

### ISSUE THREAD

**Issue by motaro** [schmittjoh/serializer#207] opened 2014-01-03 01:32 UTC
I have been searching for lot but could not find in the whole code base. I even asked on So but no one knows.

One of our old coder has coded custom `SerializationVisitor`. Now there is no documenation available on how to code custom Visitor and how to register it with JMS. But has has done and its working fine. so i am now reverse engineering it

All i wanted to ask is that at which line of code does the GRAPH navigator  call `visitProperty` method of customSerialization Visitor

The only place where i found that is

https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L227

But if i have custom handler Then system returns on line 174
https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L174

so where does visitProperty first gets called for custom serializer

**Comment by goetas** [comment] 2017-04-24 15:08
Closing, Sorry for the long feedback loop. This issue has been probably already solved, if the problem is still here, feel free to comment it and I will re-open the issue

**Closed by goetas** 2017-04-24 15:08 UTC
