### ISSUE TITLE
[feature] Handler failback

### ISSUE THREAD

**Issue by ivan1986** [schmittjoh/serializer#450] opened 2015-05-15 15:15 UTC
Add way to failback to default processing from handler
https://github.com/schmittjoh/serializer/blob/master/src/JMS/Serializer/GraphNavigator.php#L213

for example for

serializeJson(...)
{
    if ($context->[is custom view])
         return [....]
    else
         return [using default visitor]
}

i think easy way is exception

**Comment by ivan1986** [comment] 2015-06-26 11:21
#446

**Comment by goetas** [comment] 2018-03-23 08:31
duplicate of #446

**Closed by goetas** 2018-03-23 08:31 UTC
Labels: question
