### ISSUE TITLE
There is no way (that i know of) to conditionally handle the encoding of a certain type

### ISSUE THREAD

**Issue by haasalex** [schmittjoh/serializer#446] opened 2015-05-09 17:34 UTC
Under certain circumstances I want to handle the serialization of an object myself. The other times I want to have the serializer behave like normal.

Sadly, there is no way for a Handler to withdraw from processing and tell the GraphNavigator that it shall continue as if there was no handler involved.

See my ticket at http://stackoverflow.com/questions/30131615

The straight way would be to have the handler return void instead of null. Yet PHP does not distinguish between no return value and a Null return value so I don't know what's the best way to implement it.

**Comment by goetas** [comment] 2018-05-29 08:26
duplicate of https://github.com/schmittjoh/serializer/pull/177

**Closed by goetas** 2018-05-29 08:26 UTC
Labels: Feature Request
