### ISSUE TITLE
Strange issue with groups exclusion strategy

### ISSUE THREAD

**Issue by yellow1912** [schmittjoh/serializer#230] opened 2014-02-11 13:15 UTC
This ticket is related to https://github.com/FriendsOfSymfony/FOSRestBundle/issues/536

After further digging around, I found out that the serializer returns the boolean "false" when a group is set using the below syntax:

$view->setSerializationContext(SerializationContext::create()->setGroups(['list']));

However, if I add Default to the group list then it works:

$view->setSerializationContext(SerializationContext::create()->setGroups(['Default', 'list']));

Note: I'm on SF 2.4, PHP 5.5+

**Comment by bmeynell** [comment] 2015-07-15 03:59
Copied from --> https://github.com/FriendsOfSymfony/FOSRestBundle/issues/536#issuecomment-121479159

Same issue here. 

Using a simple `@Rest\View(serializerGroups={"list"})` in the controller results in the error: 

*The Response content must be a string or object implementing __toString(), "boolean" given."*

However, using `@Rest\View(serializerGroups={"Default", "list"})` works without issue. Note that I do not explicitly define a *Default* group anywhere in my entities.

Using `PHP 5.6.9-1+deb.sury.org~trusty+2` and `Symfony version 2.3.24`

**Comment by goetas** [comment] 2017-04-24 16:37
Closing, Sorry for the long feedback loop. If the problem is still here, feel free to comment (providing a failing test case) it and I will re-open the issue.

**Closed by goetas** 2017-04-24 16:37 UTC
