### ISSUE TITLE
Problem when trying do deserialize a json with an array

### ISSUE THREAD

**Issue by mdiventi** [schmittjoh/serializer#1545] opened 2024-06-21 17:43 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hello,

I'm having an issue when trying to deserialize a json object containing an array.

My model User as an array string representing the roles and it's define like below:

    /**
     * @var string[]|null
     * @SerializedName("roles")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $roles = null;
    
The error I get is : **You must define a type for App\Model\User::$roles.**

As far as my understanding goes the issue is that there is no type in the metadata for my roles property.

As indicated in the documentation the annotation Type("array<string>") should be enough for the deserializer to know the type of my roles property.

## Steps required to reproduce the problem

1. A user class containing
```
class User
{
        /**
     * @var string|null
     * @SerializedName("email")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $email = null;

    /**
     * @var string[]|null
     * @SerializedName("roles")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $roles = null;

...
```
2.  Create a json string containing
 ```
$jsonData = '{
            "email":"test@serializer.com",
            "roles": ["ROLE_ADMIN"]
}';
```
3. Use the serializer to deserialize your json

        `$myUser = $serializer->deserialize($jsonData, User::class, "json")`;

## Expected Result

* $myUser with all my properties

## Actual Result

* **You must define a type for App\Model\User::$roles.**

**Comment by scyzoryck** [comment] 2024-06-23 07:51
Hi! 
Are you sure that Annotation Driver is enabled? In the newest package version it can be disabled, so I would propose to switch to native PHP Attributes ;-)

**Comment by mdiventi** [comment] 2024-06-23 12:23
Hello,

Thank you for you quick answer.
If Annotation Driver was disabled wouldn't I have the issue with property $email too ?

While debugging I realized that the Driver used to build the metadata was TypedPropertiesDriver. In that class there is a property $allowList which, I think, is used to check if the current type is allowed.

The default value of $allowlist 
```
            'int',
            'float',
            'bool',
            'boolean',
            'string',
            'double',
            'iterable',
            'resource'
```

I then decided to make a custom DriverFactory in which the create driver does :

`$driver = new TypedPropertiesDriver($driver, $this->typeParser, ['array']);`

Adding the array as an allowed type for the MetadataDriver.

I finally used my custom driver factory in my serializer :

```
        $namingStrategy = new SerializedNameAnnotationStrategy(new IdenticalPropertyNamingStrategy());
        $this->serializer = SerializerBuilder::create()
            ->setDeserializationVisitor('json', new StrictJsonDeserializationVisitorFactory())
            ->setMetadataDriverFactory(new CustomDriverFactory($namingStrategy))
            ->build();  
```

After this I don't have the error anymore and both serialization and deserialization work well with my models.

I'm not sure if this is the right think to do and that there will be no side effects.

Regards

**Comment by scyzoryck** [comment] 2024-06-28 14:51
> If Annotation Driver was disabled wouldn't I have the issue with property $email too ?
I guess for `$email` type can be resolved by `TypedPropertiesDriver`. It do not support `array` by design as with current PHP Types we cannot type inner elements ;-) Sooo in general I would suggest to migrate

**Closed** 2024-07-03 19:21 UTC
