### ISSUE TITLE
Unserialization failure after upgrading to 3.7.0 (`excludeIf` related?)

### ISSUE THREAD

**Issue by benjamintoussaint** [schmittjoh/serializer#1207] opened 2020-05-25 09:16 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

## Steps required to reproduce the problem

1. Upgrade from 3.6.0 to 3.7.0

## Expected Result

* A working unserialization

## Actual Result

* Error when unserializing:
`{"code":500,"message":"Notice: Undefined offset: 15"}`

The `excludeIf` data appears to be missing from the `$unserialized` variable which apparently cause the `$excludeIf` property to be accidentally populated with the `parentStr` while that `$parentStr` data is missing at offset 15:

```php
public function unserialize($str)
{
    $unserialized = unserialize($str);

    [
        $this->preSerializeMethods,
        $this->postSerializeMethods,
        $this->postDeserializeMethods,
        $this->xmlRootName,
        $this->xmlRootNamespace,
        $this->xmlNamespaces,
        $this->accessorOrder,
        $this->customOrder,
        $this->discriminatorDisabled,
        $this->discriminatorBaseClass,
        $this->discriminatorFieldName,
        $this->discriminatorValue,
        $this->discriminatorMap,
        $this->discriminatorGroups,
        $this->excludeIf,
        $parentStr,
    ] = $unserialized;
```

This bug might be linked to https://github.com/schmittjoh/serializer/commit/f114dc659cf96b27a6719f844fa9c35b1ecc1a7d#diff-97e8439543c1cb6420f2765cc67bab32.

**Comment by goetas** [comment] 2020-05-25 09:17
Did you clear the cache?

**Comment by goetas** [comment] 2020-05-25 09:18
Duplicate of https://github.com/schmittjoh/JMSSerializerBundle/issues/802#issuecomment-633468609

**Closed by goetas** 2020-05-25 09:18 UTC
