### ISSUE TITLE
Version 1.8 is breaking backwards compatibility

### ISSUE THREAD

**Issue by rvanbaalen** [schmittjoh/serializer#796] opened 2017-07-12 19:55 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes

## Steps required to reproduce the problem

1. Run phpDocumentor2

## Expected Result

* Business as usual

## Actual Result

* The serializer throws an error since version 1.8:

```
[Semantical Error] The annotation "@JMS\Serializer\Annotation\Type" in property phpDocumentor\Configuration::$title does not exist, or could not be auto-loaded. in vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54
```

Related issue: https://github.com/phpDocumentor/phpDocumentor2/issues/1868

**Comment by aidantwoods** [comment] 2017-07-12 23:00
Caught this failure in my Travis cron build, here you go, incase anything in the log helps:
https://travis-ci.org/aidantwoods/SecureHeaders/jobs/252996543

**Comment by goetas** [comment] 2017-07-13 08:52
In the phpdocumentor `composer.json` file, the version constraint is `>=0.12`, that does not guarantee any BC compatibility. 

I spent some time looking at the issue, the problem is in https://github.com/phpDocumentor/phpDocumentor2/blob/develop/src/Cilex/Provider/JmsSerializerServiceProvider.php that does some path parsing (instead of using the composer autoloder).

Probably all that code can be replaced by just `AnnotationRegistry::registerLoader([$loader, 'loadClass']);` in the boostrap file (of course, not being familiar with the codebase of phpDocumentor, I'm not aware if the reasons for what they did). More info on it are available on http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/annotations.html

Closing as the issue looks to be on the phpdocumentor side.

**Closed by goetas** 2017-07-13 08:52 UTC

**Comment by rvanbaalen** [comment] 2017-07-13 10:04
Are you sure?

PhpDocumentor hasn't been updated in a while, my project has been using dev-master and was building just fine. Until this package released 1.8 a couple of days ago. At that moment the build started failing. 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by goetas** [comment] 2017-07-13 10:10
> Are you sure?

Just have a look to https://github.com/phpDocumentor/phpDocumentor2/blob/develop/src/Cilex/Provider/JmsSerializerServiceProvider.php and you will see that they rely on the folder structure, and migrating from psr-1 to psr-4 obviously changes it.

**Comment by goetas** [comment] 2017-07-13 11:34
decided to rever the PSR-4, see https://github.com/schmittjoh/serializer/issues/797
