### ISSUE TITLE
Serializing array that have one of the element or member of an element an empty object

### ISSUE THREAD

**Issue by gogume** [schmittjoh/serializer#277] opened 2014-05-26 09:09 UTC
When serializing an array that have one of the element or member of an element an empty object the whole array is transformed into an ArrayObject, is this the expected result?
I've wrote a little test here: 
https://github.com/gogume/serializer/tree/array-with-empty-object
This branch is started from the master.

**Comment by goetas** [comment] 2017-04-24 16:34
Closing, Sorry for the long feedback loop. If the problem is still here, feel free to comment (pointing out the code that presents the issue or providing a test case) it and I will re-open the issue.

**Closed by goetas** 2017-04-24 16:34 UTC
