### ISSUE TITLE
Custom type handler for doctrine entities not called after 1.6.0 ->1.70 upgrade

### ISSUE THREAD

**Issue by bblue** [schmittjoh/serializer#766] opened 2017-05-13 19:59 UTC
I am successfully using custom type handlers in` 1.5.0,` but since upgrading to `1.7.0` the handlers are no longer called for doctrine entities.  At first I thought there was some error in registering the custom handlers, but my custom handlers for non-doctrine entities still work.

Did I still miss some new configuration settings, or is this a bug? 

(I am on `dev-master `for jms/serializer-bundle, could be that the issue is with the bundle...?)

**Comment by bblue** [comment] 2017-05-13 20:12
I just testet with `1.6.0` and it works as expected. Must be some change introduced in `1.7.0 `then.

Updating the issue title to reflect that.

**Comment by goetas** [comment] 2017-05-13 20:34
duplicate of https://github.com/schmittjoh/serializer/issues/765

**Closed by goetas** 2017-05-13 20:34 UTC
Labels: duplicate
