### ISSUE TITLE
Serializing to and deserializing from DateTime is inconsistent

### ISSUE THREAD

**Issue by danwkennedy** [schmittjoh/serializer#394] opened 2015-02-09 21:33 UTC
The following mapping:

```
Our\Model\Location:
   exclusion_policy: ALL
   properties:
      updatedDateTime:
         type: DateTime<'U'>
```

Deserializes a unix timestamp correctly but serializes a DateTime object to: "2013-04-15T10:54:57+0000". I would expect a Unix timestamp to come out of the serialization process. This keeps us from having a consistent input/output for our APIs

**Comment by Nijusan** [comment] 2015-04-13 16:05
i have also a problem with serializing and deserializing a datetime.

i have an object with the following attribute:
/**
     * @var \DateTime()
     * @Serializer\Type("DateTime<'d.m.Y'>")
     */
    private $confirmationDate;

For example the Attribute is set with 'new \DateTime("18.11.2014")' and when i output with ->format(d.m.Y H:i:s) i get 18.11.2014 00:00:00
When serializing to json, i got the correct value: {"confirmation_date":"18.11.2014"...
But when deserializing back to object and output it with format i get "18.11.2014 {current local hour, minutes and seconds}"

so originalObject->confirmationDate == deserializedObject->confirmationDate is always false

**Comment by ReservedDeveloper** [comment] 2015-07-27 18:50
Bumping this thread.

**Comment by goetas** [comment] 2017-04-24 15:21
Closing, Sorry for the long feedback loop. This issue has been probably already solved, if the problem is still here, feel free to comment it and I will re-open the issue

**Closed by goetas** 2017-04-24 15:21 UTC
