### ISSUE TITLE
Dynamic property type  annotation

### ISSUE THREAD

**Issue by brpaz** [schmittjoh/serializer#436] opened 2015-04-22 11:10 UTC
I have an Entity that can be a different type of ojject depending on the situation. Is there any way I can set the "@Type" dynamically at runtime?

I tried to create a custom handler, by defining a "dummy" type annotation in my entity and then set the correct type but iits not working. allways returned empty.

My handler looks like this: (real class names ommited)

```
 public static function getSubscribingMethods()
    {
        $methods = array();
        foreach (array('json', 'xml', 'yml') as $format) {
            $methods[] = array(
                'format' => $format,
                'type' => 'MyDummyType',
            );
        }
        return $methods;

    }

    public function serializeRoomTypeTojson(JsonSerializationVisitor $visitor, $object, array $type, Context $context)
    {
        if ($object instanceof X) {
            $type = [
                'name'   => "MyContreteType",
                'params' => [

                ]
            ];

        }

        return $visitor->getNavigator()->accept($object, $type, $context);
    }
```

In my entity, i have the following:

```
    /**
     * @var Room[]
     * @Type("array<IMyDummyType>")
     */
    protected $field;
``

Any ideas?
```

**Comment by goetas** [comment] 2017-03-21 12:01
duplicate of https://github.com/schmittjoh/serializer/issues/437

**Closed by goetas** 2017-03-21 12:01 UTC
