### ISSUE TITLE
Serialization fails if root element has custom handler

### ISSUE THREAD

**Issue by Garinn** [schmittjoh/serializer#961] opened 2018-06-05 13:28 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

## Steps required to reproduce the problem

1. Register a custom serialization handler for your class
2. Try to serialize an instance of that class directly

```
class MySerializeHandler {

    public function serializeToJson(JsonSerializationVisitor $visitor, MyObject $orderSession, array $type, Context $context) {
        return ["result" => "Hi!"];
    }

   // ...

}

$object = new MyObject();
echo $serializer->serialize($object, 'json')
```

## Expected Result
`{"result" : "Hi"}`

## Actual Result
`null`

This is probably because custom handlers get executed before any `Visitor` stack processing takes place in `GraphNavigator.php`. The result of `GraphNavigator->accept` is correct, but the root property of the `Visitor` used is still `null` when accessed for the serialization result.

For comparison, if the object is embedded in any other data structure the serialization result is correct:

`echo $serializer->serialize([$object], 'json')` results in `[ {"result" : "Hi"} ]`

**Comment by goetas** [comment] 2018-06-05 13:45
duplicate of https://github.com/schmittjoh/serializer/issues/700, and solved in the upcoming 2.0 version

**Closed by goetas** 2018-06-05 13:45 UTC

**Comment by goetas** [comment] 2018-06-05 13:47
the 1.x workaround is: 

```
class MySerializeHandler {

    public function serializeToJson(JsonSerializationVisitor $visitor, MyObject $orderSession, array $type, Context $context) {
        if ($visitor->getRoot() === null){
               $visitor->setRoot(["result" => "Hi!"]);
        }
        return ["result" => "Hi!"];
    }

   // ...

}
```

**Comment by Garinn** [comment] 2018-06-05 13:51
Wow, thanks for the fast response and workaround!
